apiVersion: v1
kind: Pod
metadata:
  name: troubleshooting-pod
  namespace: rabbit
spec:
  containers:
  - name: busybox
    image: byrnedo/alpine-curl:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    stdin: true
    tty: true
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  restartPolicy: Always
